name: {{project_name.snakeCase()}}
description: {{description.snakeCase()}}

version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  generate: true
  uses-material-design: true